---
- name: Install nexus repo on Centos
  hosts: localhost
  connection: local
  become: yes

  # pre_tasks:
  #   - name: Install package dependencies.
  #     package:
  #       name: "{{ item }}"
  #       state: "present"
  #     with_items:
  #       - unzip
  #       - rsync
  
  collections:
    - jfrog.platform
    - community.general

  roles:
    - role: artifactory
      vars: 
        artifactory_enabled: true
        xray_enabled: true
