---
- name: Install gitlab 
  hosts: gitlab
  become: yes

  tasks:
    - name: Install required packages
      dnf: 
        name: {{ items }}
        state: present
      loop: 
        - curl
        - policycoreutils
        - openssh-server
        - perl
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'



