
- name: Install EPEL Repository
  shell: amazon-linux-extras install epel -y

- name: Install Daeomize
  yum: 
    name: daemonize
    state: present

- name: Install java jdk 11
  command: amazon-linux-extras install java-openjdk11 -y

- name: Download jenkins repo file
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add jenkins rpm key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install Jenkins
  yum: 
    name: jenkins
    state: present

- name: reload daemon service
  systemd:
    daemon_reload: yes

- name: Start jenkins service
  service:
    name: jenkins
    state: restarted
  
- name: Enable jenkins service on server reboot
  service:
    name: jenkins
    enabled: yes

- wait_for: 
    timeout: 60
  delegate_to: localhost

- name: jenkins init password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- debug:
    var: result.stdout
    
